# Knowledge-based Recommender System (KBRS)

Questo notebook guida attraverso le prime fasi di pre-elaborazione e arricchimento dei dati per un sistema di raccomandazione basato sulla conoscenza. Il processo si articola in tre passaggi principali:

1.  **Caricamento Dati**: Carica i file `.csv` grezzi in DataFrame di Pandas.
2.  **Preparazione Catalogo**: Unisce i dati dei film e i link per creare un catalogo unico di film.
3.  **Arricchimento Dati**: Arricchisce il catalogo film con informazioni da Wikidata e DBpedia.
4.  **Unione Dati Finali**: Unisce le valutazioni degli utenti con il catalogo arricchito.

## 1. Caricamento dei Dati
Iniziamo caricando i dataset `movies.csv`, `links.csv` e `ratings.csv` utilizzando le funzioni dal modulo `src.data_manager`.

In [1]:
import pandas as pd
import sys
import os
from IPython.display import display

# Aggiusta il percorso per l'import del modulo `src`
project_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
if project_root not in sys.path:
    sys.path.append(project_root)

from src.data_manager import load_data, join_dataframes, enrich_movies, clean_partial_rows, drop_columns, normalize_movie_data_parallel, normalize_ratings_data, compress_kbrs_dataset

# Carica i dati grezzi dai file CSV
ratings_df, movies_df, links_df = load_data()

if movies_df is not None and links_df is not None and ratings_df is not None:
    print("\n--- Dati caricati ---")
    
    print("movies.csv:", movies_df.shape)
    print("\nlinks.csv:", links_df.shape)
    print("\nratings.csv:", ratings_df.shape)
    display(movies_df.head())
    display(links_df.head())
    display(ratings_df.head())

Data loaded successfully.

--- Dati caricati ---
movies.csv: (9742, 3)

links.csv: (9742, 3)

ratings.csv: (100836, 4)

ratings.csv: (3683, 4)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
2       2    60756     will ferrell  1445714992
3       2    89774     Boxing story  1445715207
4       2    89774              MMA  1445715200

## 2. Preparazione del Catalogo Film Unico
Uniamo i DataFrame `movies` e `links` per creare un catalogo di film unici. Questo passaggio è cruciale per evitare chiamate API duplicate e rendere il processo di arricchimento efficiente.

In [2]:
unique_movie_catalog = join_dataframes(movies_df, links_df)
unique_movie_catalog = unique_movie_catalog.drop(columns=['tmdbId'])
unique_movie_catalog['imdbId'] = unique_movie_catalog['imdbId'].apply(lambda x: f"tt{int(x):07d}")

print("Catalogo film unico creato.")
print("Shape del catalogo unico:", unique_movie_catalog.shape)
display(unique_movie_catalog.head())

Catalogo film unico creato.
Shape del catalogo unico: (9742, 4)

,movieId,title,genres,imdbId
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,tt0114709
1,2,Jumanji (1995),Adventure|Children|Fantasy,tt0113497
2,3,Grumpier Old Men (1995),Comedy|Romance,tt0113228
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,tt0114885
4,5,Father of the Bride Part II (1995),Comedy,tt0113041

## 3. Arricchimento del Catalogo Film
Ora arricchiamo il catalogo unico di film con i dati semantici di Wikidata e DBpedia. La funzione `enrich_movies` gestirà le chiamate API in batch e mostrerà l'avanzamento con una barra di caricamento.

In [3]:
enriched_movie_catalog = enrich_movies(unique_movie_catalog)

print("\n--- Dati arricchiti ---")
print("Shape del catalogo arricchito:", enriched_movie_catalog.shape)
enriched_movie_catalog = drop_columns(enriched_movie_catalog, ['title', 'imdbId', 'dbpediaAbstract', 'wikidataId'])
display(enriched_movie_catalog.head())

Checkpoint found: 'data/processed/dbpedia_data.csv'. Resuming...
No new movies to process. Returning existing data.

--- Dati arricchiti ---
Shape del catalogo arricchito: (9742, 9)

,movieId,genres,dbpediaDirector,dbpediaRuntime,dbpediaActors
0,1,Adventure|Animation|Children|Comedy|Fantasy,John Lasseter,4860.0,John Ratzenberger|Annie Potts|Tom Hanks|Erik v...
1,2,Adventure|Children|Fantasy,Joe Johnston,6240.0,Robin Williams|Bebe Neuwirth|Bonnie Hunt|David...
2,3,Comedy|Romance,Howard Deutch,6060.0,Ann-Margret|Walter Matthau|Daryl Hannah|Jack L...
3,4,Comedy|Drama|Romance,Forest Whitaker,7440.0,Angela Bassett|Lela Rochon|Loretta Devine|Whit...
4,5,Comedy,Charles Shyer,6360.0,George Newbern|Steve Martin|Eugene Levy|Kieran...

## 4. Pulizia dati vuoti

In [4]:
cleaned_df = None

try:
    # Call the cleaning function
    cleaned_df = clean_partial_rows(enriched_movie_catalog)
except Exception as e:
    print(f"An unexpected error occurred: {e}")

--- Cleaning Report ---
Total records before cleaning: 9742
Total records after cleaning: 8024
Deleted records: 1718

Empty records per column (before cleaning):
movieId               0
genres                0
dbpediaDirector    1101
dbpediaRuntime      672
dbpediaActors      1258

Cleaned data has been saved to 'data/processed/dbpedia_data_cleaned.csv'.

## 5. Normalizzazione dei dati
In questo passaggio le colonne numeriche vengono normalizzate da 0 a 1 e quelle testuali in one-hot encoding.

In [5]:
normalized_data= None

if cleaned_df is not None:
    normalized_data = normalize_movie_data_parallel(cleaned_df)
    print(normalized_data.shape)
    
    normalized_ratings = normalize_ratings_data(ratings_df)

Fase 1/3: Raccolta e selezione delle feature uniche...

Raccolta Metadati: 100%|██████████| 8024/8024 [00:00<00:00, 59569.81it/s]

Fase 2/3: Normalizzazione dei dati numerici...
Fase 3/3: Elaborazione in parallelo con 8 core...

Elaborazione in Parallelo: 100%|██████████| 41/41 [00:00<00:00, 661409.48it/s]

Elaborazione completata. Risultato salvato in data/processed/normalized_movies_optimized.csv
(8024, 16112)
Fase 1/2: Normalizzazione del punteggio...
Fase 2/2: Creazione di una matrice di interazione sparsa (User-Item)...

In [6]:
    display(normalized_data.head())
    display(normalized_ratings.head())

,movieId,genre_(no genres listed),genre_Action,genre_Adventure,genre_Animation,genre_Children,genre_Comedy,genre_Crime,genre_Documentary,genre_Drama,...,actor_Émilien Néron,actor_Éric Berger,actor_Éric Judor,actor_Érica Rivas,actor_Óscar Jaenada,actor_Özge Özberk,actor_Đơn Dương,actor_Şerif Sezer,actor_Željko Ivanek,runtime_normalized
0,1,0,0,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0.358170
1,2,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.388235
2,3,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0.384314
3,4,0,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0.414379
4,5,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0.390850

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,0.777778,0.0,0.777778,0.0,0.0,0.777778,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.777778,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## 6. Reduce data dimension
Application of TrunctedSVD to get a lighter representation of the data.

In [11]:
compressed_df = None

if normalized_data is not None:
    compressed_df = compress_kbrs_dataset(normalized_data, 4096)

Fase 1/3: Preparazione dei dati...
Dataset originale: 8024 righe, 16111 colonne.
Dimensioni occupate in memoria (stimato, solo features): 0.60 MB
Fase 2/3: Applicazione di TruncatedSVD con 4096 componenti...

Calcolo SVD: 100%|██████████| 1/1 [00:51<00:00, 51.90s/it]

Fase 3/3: Creazione del nuovo DataFrame compresso...
Dataset compresso: 8024 righe, 4097 colonne.
Varianza spiegata: 0.9214

In [12]:
compressed_df.to_csv("data/processed/compressed_movie_catalog.csv", index=False)